apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  AIRFLOW_HOME: "/opt/airflow"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
  AIRFLOW__CORE__LOAD_EXAMPLES: "True"
  AIRFLOW__CORE__EXECUTOR: "KubernetesExecutor"
  AIRFLOW__CORE__DEFAULT_TIMEZONE: "America/Sao_Paulo"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET: "sql_alchemy_conn"
  AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT: "False"
  AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: "/opt/airflow/pod_template.yaml"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "localhost:32000/airflow"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "latest"
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: "airflow"
  AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
  AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
  #AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/dags/logs"
  #AIRFLOW__CORE__DAG_PROCESSOR_MANAGER_LOG_LOCATION: "/opt/airflow/dags/logs"
  #AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY: "/opt/airflow/dags/logs"