---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeName: microk8s-01
      volumes:
        - name: mysql
          emptyDir:
            sizeLimit: 500Mi
      containers:
      - name: mysql
        image: mysql:8-debian
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "passw0rd"
          - name: MYSQL_DATABASE
            value: "airflow"
          - name: MYSQL_USER
            value: "airflow"
          - name: MYSQL_PASSWORD
            value: "airflow"
---        
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306