---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-airflow
  namespace: airflow
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.122.101
  share: /srv/nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: airflow-dags
#   namespace: airflow
# spec:
#   storageClassName: nfs-airflow
#   accessModes:
#     - ReadOnlyMany
#   capacity:
#     storage: 2Gi
#   mountOptions:
#     - nosuid
#   nfs:
#     server: 192.168.122.101
#     path: "/airflow-dags"
#     readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-dags
  namespace: airflow
spec:
  storageClassName: nfs-airflow
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
#  volumeName: airflow-dags
# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: airflow-logs
#   namespace: airflow
# spec:
#   storageClassName: nfs-airflow
#   accessModes:
#     - ReadOnlyMany
#   capacity:
#     storage: 2Gi
#   mountOptions:
#     - nosuid
#   nfs:
#     server: 192.168.122.101
#     path: "/airflow-logs"
#     readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-logs
  namespace: airflow
spec:
  storageClassName: nfs-airflow
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
#  volumeName: airflow-logs